# create your drupal and postgres config here, based off the last assignment
version: '2'

services:
  cms:
    image: custom-drupal
    build: .
    ports:
      - '8080:80'
    volumes:
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles
      - drupal-sites:/var/www/html/sites
      - drupal-themes:/var/www/html/themes
  database:
    image: postgres:14
    environment:
      - POSTGRES_PASSWORD=example
    volumes:
      - drupal-data:/var/lib/postgresql/data

volumes:
  drupal-data:
  drupal-modules:
  drupal-profiles:
  drupal-sites:
  drupal-themes:
